### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by sweepyoface** [ladjs/koa-better-error-handler#11]
Would love to use this in my TS project.

**Comment by niftylettuce** [comment]
I do not support TypeScript, it is not open-source friendly for the JavaScript community nor GitHub.

**Comment by vkarpov15** [comment]
@niftylettuce I'd love to hear your reasons why. Not criticizing or disagreeing, just want to hear your reasons for academic curiosity

**Comment by niftylettuce** [comment]
IMO TypeScript is horrible and the community doesn't need yet another CoffeeScript, the main reason being the latter.

**Comment by sweepyoface** [comment]
Sorry, no.

TypeScript is a completely separate project that brings only **objective benefits** over JavaScript, and is growing rapidly. Pure JavaScript development has already been deprecated by a lot of people.

You can choose to not maintain your project out of laziness, but that excuse is simply not valid.

**Comment by vkarpov15** [comment]
@sweepyoface this isn't my project so I can't speak for @niftylettuce , but your tone is not appropriate for a constructive discussion. This is a JavaScript project, the maintainers have zero obligation to support typescript. And for every typescript purist, theres plenty of people that think TS is bloated and not worth the effort.

Here's a thought: would you or your company consider paying for TS bindings?

**Comment by niftylettuce** [comment]
@sweepyoface I'm a veteran in the community, and from one look at your GitHub profile you truly don't have any open source experience, unless you have aliases I don't know about.  Please do not submit issues to my projects about TypeScript again, thank you though.

And no, I'm not lazy.  I am co-founder and CTO of a company and I still find time to maintain hundreds of packages.

![Screen Shot 2019-04-19 at 3 40 46 PM](https://user-images.githubusercontent.com/523141/56443282-8ddc2f00-62b9-11e9-846b-7ee66bd012db.png)
