### ISSUE TITLE
Possibility to enumerate errors.

### ISSUE THREAD

**Issue by colthreepv** [ladjs/koa-better-error-handler#13]
What I would like is:

```javascript
ctx.throw(
  new Boom('Trying to create an already existing element', { statusCode: 409, decorate: { code: 101 } })
)
```

Important part here being `{ decorate: { code: 101 } }`
If that information would be forwarded to the JSON produced from koa, the user could get a numeric reference to that error.

That is useful for a number of purposes

As i seen through the code, this line seems to be my enemy: [index.js#L91](https://github.com/ladjs/koa-better-error-handler/blob/master/src/index.js#L91)
since it makes a new Boom error, it cannot use the object I created before

**Comment by niftylettuce** [comment]
Hi @colthreepv sorry for the delay in following up - a PR is welcome 😄

**Comment by niftylettuce** [comment]
PR welcome
