### ISSUE TITLE
Add check for `ctx.res.headersSent`

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/koa-better-error-handler#6]

**Comment by niftylettuce** [comment]
e.g. https://github.com/koajs/koa/blob/53a44461230199fd175a9f1c77ba66c7943bfaf5/lib/application.js#L222

**Comment by pablopunk** [comment]
Isn't this already done here?

https://github.com/ladjs/koa-better-error-handler/blob/master/src/index.js#L91

Or you mean we should check it here with `this.res.headersSent`

https://github.com/ladjs/koa-better-error-handler/blob/master/src/index.js#L194

**Comment by niftylettuce** [comment]
could you write a test or two to try to break it @pablopunk?

also we might need to move our code around a bit to match this https://github.com/koajs/koa/blob/6baa41178d3930df399fb367dbc3d73890760e02/lib/context.js#L111-L124 (we should set the property on the `err`)

**Comment by niftylettuce** [comment]
in terms of tests, you'd have a request hit a route like `/break-headers-sent` and it'd send a response but move along to the error handler as well

**Comment by niftylettuce** [comment]
but you're right - I think it is already done, though several times I got the "Headers already sent" error.

**Comment by pablopunk** [comment]
@niftylettuce okay, I wrote a test that breaks it, I'll fix it 👍🏻

**Comment by niftylettuce** [comment]
amazing, thank you @pablopunk !
